### ISSUE TITLE
Can't use Golang plugin in IntelliJ community edition

### ISSUE THREAD

**Issue by nella17** [verizon-media-2019-ais3/identity-service#69]
![Screen Shot 2019-07-23 at 11 43 34 AM](https://user-images.githubusercontent.com/14134195/61681217-311c6480-ad3f-11e9-80e2-83ffbc427521.jpg)

**Comment by sleepingpig** [comment]
Sorry for the late response. 
Are you able to download and install from https://plugins.jetbrains.com/plugin/9568-go directly?
Please take care of the version to download for your IntelliJ version.

**Comment by nella17** [comment]
Yes, I use 2019.1.3 community version that time.
But I download 2019.2 community version can use golang plugin.
![Screen Shot 2019-07-25 at 12 56 25 PM](https://user-images.githubusercontent.com/14134195/61847127-26e39d00-aedc-11e9-9932-c462435f95ce.jpg)
