### ISSUE TITLE
sudo apt-get install go

### ISSUE THREAD

**Issue by LJP-TW** [verizon-media-2019-ais3/identity-service#70]
Here: https://github.com/verizon-media-2019-ais3/identity-service/wiki/Environment-Setup#golang

```
sudo apt-get install go # Ubuntu
```

According to this: https://github.com/riking/joycon/issues/40
> The package name is golang in latest ubuntu and other distros.
It should be
```
sudo apt-get install golang # Ubuntu
```

**Comment by sleepingpig** [comment]
Thanks, I've updated the instructions.
